Btrfs compression
ChimeraOS/chimeraos pull request #889
Opened 2024-03-09 13:57 UTC by NeroReflex

Enable btrfs compression at build-time as well as run-time.

The image boots and game just fine and I haven't seen any noticeable slowdown or system load in any of my device.

Chosen compression levels are to achieve minimal image size when building in github and installing to the end-user system and fast write speed for the user (since subvolumes are mounted with a much less aggressive compression ratio).

2024-03-09 16:17 UTC, alkazar commented
My understanding was that compression requires copy on write, which we have disabled.

2024-03-10 00:32 UTC, NeroReflex commented
> My understanding was that compression requires copy on write, which we have disabled.

I haven't read that. Can you point me to it? Beside is it disabled in github ci too?

2024-03-11 08:34 UTC, honjow commented
A glaring mistake, it should be "compress-force" instead of "force-compress."

2024-03-28 16:40 UTC, pastaq requested changes
https://btrfs.readthedocs.io/en/latest/ch-mount-options.html#btrfs-specific-mount-options

2024-03-29 16:57 UTC, NeroReflex commented
> A glaring mistake, it should be "compress-force" instead of "force-compress."

Thank you for spotting that!

@pastaq and @alkazar I have also removed nodatacow to effectively allow compression and defragmented the filesystem.

A subvolume created without nodatacow can be mounted with that flag and vice-versa.

2024-04-01 13:33 UTC, merged